# Eigenvalues and eigenvectors
### Using power iteration and deflation techniqwes to find *largest and 2nd largest eigenvalues* of the given matrix.
### Should hand in one source code and one pdf. file

In [149]:
import numpy as np

In [150]:
A=np.array([
    [190,66,-84,30],
    [66,303,42,-36],
    [336,-168,147,-112],
    [30,-36,28,291]
])
print('A=')
print(A)

w,v=np.linalg.eig(A)
print(w)

A=
[[ 190   66  -84   30]
 [  66  303   42  -36]
 [ 336 -168  147 -112]
 [  30  -36   28  291]]
[147.+196.j 147.-196.j 294.  +0.j 343.  +0.j]


In [151]:
def powermethod(A, epsl):
    ### input: A matrix, epsl(1.0e-15)
    ### initial set
    itmax=100
    x=np.random.random((4,1))  ## initial set of x_0 (4*1)
    k=0
    lamb0=1.0  ## initial guess about lambda
    rel_diff=1.0  ## initial difference of lambda(by cal. and true) 
    
    ### loop
    while((k<itmax) and (rel_diff>epsl)):
        v=A.dot(x)
        lamb1=np.linalg.norm(v)
        x=v/lamb1
        rel_diff=abs((lamb1-lamb0)/lamb0)
        
        k=k+1
        lamb0=lamb1
        #print('k=', k, 'lambda_1=', lamb1, 'error=', rel_diff)
        #print('v1=', x)
        #print('=======')
    
    return A, lamb1, x, rel_diff
    
def deflation(A, lamb1,x):
    ### B=A-lamb1*v1*x^T
    ### x^T*v1=1
    v=x
    x_1=1/v.item(0)
    B_x=np.array([x_1,0,0,0],dtype=object)
    #print(v)
    #print(B_x)
    
    ### Set B
    vxT=np.zeros(shape=(4,4))
    for i in range(4):
        for j in range(4):
            vxT[i][j]=v[i]*B_x[j]
    #print(vxT)
    B=A-lamb1*vxT
    #print(B)    ### DONE!
    
    ### apply power method to B
    B,lamb2,v2,err2=powermethod(B,1.0e-5)
    
    return B, lamb2, v2, err2

### Main function
def find2Eigval(A,epsl):
    A, lamb1, x, err1=powermethod(A,epsl)
    B, lamb2, v2,err2=deflation(A,lamb1,x)
    print('First eigenvalue is:',lamb1, '; Error is:', err1)
    print('Second eigenvalue is:',lamb2, '; Error is:', err2)

In [152]:
find2Eigval(A,1.0e-5)

First eigenvalue is: 342.99252407133827 ; Error is: 7.869261889590079e-06
Second eigenvalue is: 294.9112866691407 ; Error is: 3.5105843783451157e-06
